### ISSUE TITLE
Windows availability

### ISSUE THREAD

**Issue by pidgeon777** [2KAbhishek/tdo#11]
Hello, I was wondering if `tdo` is available also for Windows.

**Comment by 2KAbhishek** [comment]
You can run it on windows if you have bash installed there, along with the other required programs

WSL would be the best way to do it, or I'd recommend trying out scoop to install the dependencies

**Comment by 2KAbhishek** [comment]
@pidgeon777 let me know if you need any help with this or have any follow up questions, closing this till then
