### ISSUE TITLE
[BUG]: Fish shell install script

### ISSUE THREAD

**Issue by idr4n** [2KAbhishek/tdo#3]
### Description of the bug

Hi there,

I'm just trying your note taking system which looks pretty good and simple. Looking forward to use it in my workflow.

I noticed that the install script uses `export PATH="$HOME/.local/bin:$PATH"` and `export NOTES_DIR=$NOTES_DIR`. However, when using fish one should use the command `fish_add_path` or add `set -gx PATH $PATH $HOME/.local/bin` to the config file instead. Not sure if `export PATH="$HOME/.local/bin:$PATH"` even works as I replaced it right away with the second option mentioned.

### Steps To Reproduce

Run the install script and `export PATH="$HOME/.local/bin:$PATH"` is added to `~/.config/fish/config.fish`.

**Comment by 2KAbhishek** [comment]
Thanks for raising this issue, I have not used fish for a long time hence the oversight, it looks like we need to add another conditional for fish.

Can you list down the alternative commands that worked for you? I can tey adding them in.

And if you are interested feel free to open up a PR for this fix too

**Comment by idr4n** [comment]
> And if you are interested feel free to open up a PR for this fix too

Yes, definitely, I will do some testing on my end and will soon open up a PR.
