### ISSUE TITLE
[QUESTION]: cd into root when creating notes

### ISSUE THREAD

**Issue by idr4n** [2KAbhishek/tdo#7]
### Description

Hi there,

When I find a note with `tdo f` the function `find_note` cd into root. I was wondering if there is a particular reason why this behavior is not added when creating notes, e.g. with `tdo e` or `tdo t`.

Particularly, I would like to automatically cd into root whenever creating notes from any other path or directory outside of root. That is, to add `cd "$root" || return` to functions such as `new_todo` and `new_entry`.

Let me know if you would like to consider a PR for this.

Thanks in advance!

**Comment by 2KAbhishek** [comment]
Thanks for opening up the issue.

I wanted to understand what problem are you facing for this feature not being present.

Can you share some more details on that please.

**Comment by idr4n** [comment]
It is not a problem as such, but if I crate a note, at which point neovim is opened (as it is my editor), then neo-tree or nvimtree for example, will not show the right directory and therefore it is difficult to locate the newly created note. Also, if I want to fuzzy find something (e.g., with Telescope) then it would not be possible or difficult. This is because, most of the time after creating a note, I want to interact with the rest of my notes dir or vault (also, I am using `obsidian.nvim` which will not detect the right notes directory, therefore).

**Comment by 2KAbhishek** [comment]
Ahh right, I am aware of this and it was intentional since neovim uses the tdo script in non interactive mode. 

I personally use a keybinding that let's me quickly change the root to the parent of the current file: https://github.com/2KAbhishek/nvim2k/blob/13cb15d51e9ccc5ffa02e08b925d4642a3221722/lua/plugins/tools/which-key.lua#L126

You can also write a lua function that can do the same but change to git root instead of file root.

**Comment by 2KAbhishek** [comment]
Just pushed out a neovim command to handle git root / parent dir

You can check it out here: https://github.com/2KAbhishek/nvim2k/commit/a96091ee9e8b93ed685f1b7a74ebf6cc53fb4883

If this addresses your concern, feel free to close the issue as well

**Comment by idr4n** [comment]
Thanks for elaborating on that. Not sure what you mean by "neovim uses the tdo script in non interactive mode" though.

I do have a similar command for changing the current directory in neovim (which I never use actually), but in my case, since whenever I interact with a note I want the notes directory to be set as the cwd, changing the cwd manually would add another step in my workflow.

At the moment I am happy by adding `cd "$current_dir" || return` to the functions that create notes, as it is working as expected so far for me. So I'm going to close this issue given that you preference is to not cd into the notes directory overall when creating notes.

Thanks again!

**Comment by 2KAbhishek** [comment]
I was referring to the https://github.com/2kabhishek/tdo.nvim plugin.

This executes the script non interactively.

**Comment by 2KAbhishek** [comment]
Hey @idr4n I was going through the code and found a way to handle the case you mentioned without breaking compatibility with the neovim extension, I have pushed out a fix :)

**Comment by idr4n** [comment]
Thank @2KAbhishek. However I was referring to the functions that create notes, such as `new_note`, `new_todo` and `new_entry`.

**Comment by 2KAbhishek** [comment]
yes, they have been updated to cd into the root dir beofre opening neovim. check the `write_file` code

**Comment by idr4n** [comment]
Oh yes, I missed that. Thanks a lot @2KAbhishek, it is working as desired!
